Repository SeSAC-Ermes/Epari-backend, pull requests merged in 2024-11, with the labels that each got.

#4 [TEST] 테스트
  README.md
Labels: documentation

#8 [FEAT] 학습 관리 시스템(LMS) 도메인 엔티티 설계
  src/main/java/com/example/epari/assignment/domain/Assignment.java
  src/main/java/com/example/epari/assignment/domain/AssignmentFile.java
  src/main/java/com/example/epari/assignment/domain/Submission.java
  src/main/java/com/example/epari/assignment/domain/SubmissionFile.java
  src/main/java/com/example/epari/board/domain/Answer.java
  src/main/java/com/example/epari/board/domain/AnswerFile.java
  src/main/java/com/example/epari/board/domain/BoardQuestion.java
  src/main/java/com/example/epari/board/domain/Comment.java
  src/main/java/com/example/epari/board/domain/Notice.java
  src/main/java/com/example/epari/board/domain/NoticeFile.java
  src/main/java/com/example/epari/board/domain/QuestionFile.java
  src/main/java/com/example/epari/exam/domain/Choice.java
  src/main/java/com/example/epari/exam/domain/Exam.java
  src/main/java/com/example/epari/exam/domain/ExamQuestion.java
  src/main/java/com/example/epari/exam/domain/ExamResult.java
  src/main/java/com/example/epari/exam/domain/ExamScore.java
  src/main/java/com/example/epari/exam/domain/MultipleChoiceQuestion.java
  src/main/java/com/example/epari/exam/domain/QuestionImage.java
  src/main/java/com/example/epari/exam/domain/SubjectiveQuestion.java
  src/main/java/com/example/epari/global/common/base/BaseFile.java
  src/main/java/com/example/epari/global/common/base/BaseTimeEntity.java
  src/main/java/com/example/epari/global/common/base/BaseUser.java
  src/main/java/com/example/epari/global/common/enums/AttendanceStatus.java
  src/main/java/com/example/epari/global/common/enums/BoardQuestionType.java
  src/main/java/com/example/epari/global/common/enums/DayOfWeek.java
  src/main/java/com/example/epari/global/common/enums/ExamQuestionType.java
  src/main/java/com/example/epari/global/common/enums/ExamStatus.java
  src/main/java/com/example/epari/global/common/enums/NoticeType.java
  src/main/java/com/example/epari/global/common/enums/SubmissionStatus.java
  src/main/java/com/example/epari/global/common/enums/UserRole.java
  src/main/java/com/example/epari/lecture/domain/Attendance.java
  src/main/java/com/example/epari/lecture/domain/Curriculum.java
  src/main/java/com/example/epari/lecture/domain/Lecture.java
  src/main/java/com/example/epari/lecture/domain/LectureContent.java
  src/main/java/com/example/epari/lecture/domain/LectureContentFile.java
  src/main/java/com/example/epari/lecture/domain/LectureStudent.java
  src/main/java/com/example/epari/user/domain/Instructor.java
  src/main/java/com/example/epari/user/domain/ProfileImage.java
  src/main/java/com/example/epari/user/domain/Student.java
  src/main/resources/application.properties
Labels: enhancement

#11 [FEAT] 개발을 위한 초기 데이터 구성
  src/main/java/com/example/epari/global/config/JpaConfig.java
  src/main/java/com/example/epari/global/init/InitDataLoader.java
  src/main/java/com/example/epari/lecture/repository/AttendanceRepository.java
  src/main/java/com/example/epari/lecture/repository/CurriculumRepository.java
  src/main/java/com/example/epari/lecture/repository/LectureRepository.java
  src/main/java/com/example/epari/lecture/repository/LectureStudentRepository.java
  src/main/java/com/example/epari/user/repository/InstructorRepository.java
  src/main/java/com/example/epari/user/repository/StudentRepository.java
Labels: enhancement

#16 [FEAT] 과제 기본 CRUD api 구현
  src/main/java/com/example/epari/assignment/controller/AssignmentController.java
  src/main/java/com/example/epari/assignment/dto/AssignmentRqDto.java
  src/main/java/com/example/epari/assignment/repository/AssignmentRepository.java
  src/main/java/com/example/epari/assignment/service/AssignmentService.java
Labels: enhancement

#17 [FEAT] Cognito를 적용한 일반 로그인 기능 구현
  build.gradle
  src/main/java/com/example/epari/global/auth/controller/AuthController.java
  src/main/java/com/example/epari/global/config/security/SecurityConfig.java
Labels: enhancement

#18 [FEAT] 강의 CRUD 기능 구현
  src/main/java/com/example/epari/global/init/InitDataLoader.java
  src/main/java/com/example/epari/lecture/controller/LectureController.java
  src/main/java/com/example/epari/lecture/domain/Lecture.java
  src/main/java/com/example/epari/lecture/dto/curriculum/curriculumReponseDto.java
  src/main/java/com/example/epari/lecture/dto/curriculum/curriculumRequestDto.java
  src/main/java/com/example/epari/lecture/dto/lecture/LectureRequestDto.java
  src/main/java/com/example/epari/lecture/dto/lecture/LectureResponseDto.java
  src/main/java/com/example/epari/lecture/repository/LectureRepository.java
  src/main/java/com/example/epari/lecture/service/LectureService.java
  src/main/java/com/example/epari/user/repository/InstructorRepository.java
  src/main/java/com/example/epari/user/repository/StudentRepository.java
Labels: enhancement

#21 [FEAT] 사용자 역할 기반 접근 제어 설정
  src/main/java/com/example/epari/global/annotation/CurrentUserEmail.java
  src/main/java/com/example/epari/global/config/security/SecurityConfig.java
Labels: enhancement

#25 [FIX] 빌드 오류 원인 분석 및 수정
  .gitignore
  build.gradle
  src/test/java/com/example/epari/EpariBackendApplicationTests.java
  src/test/resources/application.properties
Labels: bug

#27 [FEAT] 시험 생성 및 특정 강의 시험 목록 조회 기능 구현
  src/main/java/com/example/epari/exam/controller/ExamController.java
  src/main/java/com/example/epari/exam/domain/Exam.java
  src/main/java/com/example/epari/exam/dto/request/ExamRequestDto.java
  src/main/java/com/example/epari/exam/dto/response/ExamResponseDto.java
  src/main/java/com/example/epari/exam/repository/ExamRepository.java
  src/main/java/com/example/epari/exam/service/ExamService.java
Labels: enhancement

#29 [FEAT] 과제 API CRUD 및 파일 업로드 기능 구현
  src/main/java/com/example/epari/assignment/controller/AssignmentController.java
  src/main/java/com/example/epari/assignment/domain/Assignment.java
  src/main/java/com/example/epari/assignment/domain/AssignmentFile.java
  src/main/java/com/example/epari/assignment/dto/AssignmentRqDto.java
  src/main/java/com/example/epari/assignment/dto/assignment/AssignmentRequestDto.java
  src/main/java/com/example/epari/assignment/dto/assignment/AssignmentResponseDto.java
  src/main/java/com/example/epari/assignment/dto/file/AssignmentFileResponseDto.java
  src/main/java/com/example/epari/assignment/repository/AssignmentFileRepository.java
  src/main/java/com/example/epari/assignment/service/AssignmentService.java
Labels: enhancement

#34 [FEAT] 사용자 역할 기반 강의 조회 및 AWS S3 컨텐츠 관리 기능 구현
  build.gradle
  src/main/java/com/example/epari/global/common/repository/BaseUserRepository.java
  src/main/java/com/example/epari/global/common/service/S3FileService.java
  src/main/java/com/example/epari/global/config/aws/AwsS3Config.java
  src/main/java/com/example/epari/global/config/aws/AwsS3Properties.java
  src/main/java/com/example/epari/lecture/controller/LectureContentController.java
  src/main/java/com/example/epari/lecture/controller/LectureController.java
  src/main/java/com/example/epari/lecture/domain/LectureContent.java
  src/main/java/com/example/epari/lecture/dto/content/LectureContentRequestDto.java
  src/main/java/com/example/epari/lecture/dto/content/LectureContentResponseDto.java
  src/main/java/com/example/epari/lecture/dto/lecture/LectureResponseDto.java
  src/main/java/com/example/epari/lecture/repository/LectureContentRepository.java
  src/main/java/com/example/epari/lecture/repository/LectureRepository.java
  src/main/java/com/example/epari/lecture/service/LectureContentService.java
  src/main/java/com/example/epari/lecture/service/LectureService.java
  src/main/resources/application.properties
Labels: enhancement

#35 [REFACTOR] Assignment 엔티티 일부 필드 삭제 및 불필요한 로직 정리
  src/main/java/com/example/epari/assignment/controller/AssignmentController.java
  src/main/java/com/example/epari/assignment/domain/Assignment.java
  src/main/java/com/example/epari/assignment/repository/AssignmentFileRepository.java
  src/main/java/com/example/epari/assignment/service/AssignmentService.java
Labels: enhancement

#37 [FEAT] 출석 상태 변경 엔드포인트 구현
  src/main/java/com/example/epari/assignment/dto/assignment/AssignmentResponseDto.java
  src/main/java/com/example/epari/lecture/controller/AttendanceController.java
  src/main/java/com/example/epari/lecture/domain/Attendance.java
  src/main/java/com/example/epari/lecture/dto/attendance/AttendanceResponseDto.java
  src/main/java/com/example/epari/lecture/dto/attendance/AttendanceUpdateDto.java
  src/main/java/com/example/epari/lecture/repository/AttendanceRepository.java
  src/main/java/com/example/epari/lecture/service/AttendanceService.java
Labels: enhancement

#44 [FEAT] 시험 정보 상세 조회, 수정, 삭제 기능 구현
  src/main/java/com/example/epari/exam/controller/ExamController.java
  src/main/java/com/example/epari/exam/repository/ExamRepository.java
  src/main/java/com/example/epari/exam/service/ExamService.java
Labels: enhancement

#46 [REFACTOR] 배포를 위한 코드 리팩토링(CORS Origin, properties 파일 등)
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/com/example/epari/assignment/controller/AssignmentController.java
  src/main/java/com/example/epari/global/config/security/CorsProperties.java
  src/main/java/com/example/epari/global/config/security/SecurityConfig.java
  src/main/resources/application-prod.yaml
  src/main/resources/application.properties
  src/main/resources/application.yaml
Labels: enhancement

#49 [FEAT] 과제 리스트 조회 및 과제 출제 구현
  src/main/java/com/example/epari/assignment/controller/AssignmentController.java
  src/main/java/com/example/epari/assignment/repository/AssignmentRepository.java
  src/main/java/com/example/epari/assignment/service/AssignmentService.java
Labels: enhancement

#52 [REFACTOR] 강의 수정 로직 개선 및 개별 파일 삭제 기능 추가
  src/main/java/com/example/epari/course/controller/CourseContentController.java
  src/main/java/com/example/epari/course/domain/CourseContent.java
  src/main/java/com/example/epari/course/dto/content/CourseContentRequestDto.java
  src/main/java/com/example/epari/course/dto/content/CourseContentResponseDto.java
  src/main/java/com/example/epari/course/service/CourseContentService.java
Labels: enhancement, refactoring

#54 [Refactor] 과제 상세 조회, 목록 로직 개선
  src/main/java/com/example/epari/assignment/controller/AssignmentController.java
  src/main/java/com/example/epari/assignment/domain/Assignment.java
  src/main/java/com/example/epari/assignment/dto/assignment/AssignmentResponseDto.java
  src/main/java/com/example/epari/assignment/repository/AssignmentRepository.java
  src/main/java/com/example/epari/assignment/service/AssignmentService.java
Labels: refactoring

#53 [FEAT] 공지사항 CRUD 구현 후 API로 확인
  src/main/java/com/example/epari/board/controller/FileController.java
  src/main/java/com/example/epari/board/controller/NoticeController.java
  src/main/java/com/example/epari/board/domain/AnswerFile.java
  src/main/java/com/example/epari/board/domain/BoardQuestion.java
  src/main/java/com/example/epari/board/domain/Notice.java
  src/main/java/com/example/epari/board/domain/NoticeFile.java
  src/main/java/com/example/epari/board/domain/QuestionFile.java
  src/main/java/com/example/epari/board/dto/FileInfoDto.java
  src/main/java/com/example/epari/board/dto/NoticeFileDto.java
  src/main/java/com/example/epari/board/dto/NoticeRequestDto.java
  src/main/java/com/example/epari/board/dto/NoticeResponseDto.java
  src/main/java/com/example/epari/board/repository/NoticeFileRepository.java
  src/main/java/com/example/epari/board/repository/NoticeRepository.java
  src/main/java/com/example/epari/board/service/FileService.java
  src/main/java/com/example/epari/board/service/NoticeService.java
Labels: enhancement

#58 [FEAT] 당일 자료 강의 자료 조회 구현
  src/main/java/com/example/epari/course/controller/CourseContentController.java
  src/main/java/com/example/epari/course/service/CourseContentService.java
Labels: enhancement

#60 [FEAT] 과제 생성 시 S3 파일 업로드 기능 구현
  .gitignore
  src/main/java/com/example/epari/assignment/controller/AssignmentController.java
  src/main/java/com/example/epari/assignment/domain/AssignmentFile.java
  src/main/java/com/example/epari/assignment/dto/assignment/AssignmentRequestDto.java
  src/main/java/com/example/epari/assignment/service/AssignmentService.java
Labels: enhancement

#65 [FEAT] 커리큘럼 조회 엔드포인트 구현
  src/main/java/com/example/epari/course/controller/CurriculumController.java
  src/main/java/com/example/epari/course/dto/curriculum/CurriculumResponseDto.java
  src/main/java/com/example/epari/course/dto/curriculum/curriculumReponseDto.java
  src/main/java/com/example/epari/course/dto/curriculum/curriculumRequestDto.java
  src/main/java/com/example/epari/course/repository/CurriculumRepository.java
  src/main/java/com/example/epari/course/service/CurriculumService.java
Labels: enhancement

#66 [REFACTOR] 강의 프로필 이미지 필드 추가
  src/main/java/com/example/epari/course/domain/Course.java
  src/main/java/com/example/epari/course/dto/course/CourseResponseDto.java
  src/main/java/com/example/epari/global/common/service/S3FileService.java
  src/main/java/com/example/epari/global/init/InitDataLoader.java
Labels: enhancement

#69 [REFACTOR] S3 설정값 주입 어노테이션 추가
  src/main/java/com/example/epari/global/config/aws/AwsS3Properties.java
Labels: refactoring

#73 [FIX] S3 설정 주입 어노테이션 제거
  src/main/java/com/example/epari/global/config/aws/AwsS3Properties.java
Labels: bug

#74 [FEAT] 시험 문제 생성, 수정, 삭제 기능 구현
  src/main/java/com/example/epari/exam/controller/ExamController.java
  src/main/java/com/example/epari/exam/controller/ExamQuestionController.java
  src/main/java/com/example/epari/exam/controller/InstructorExamController.java
  src/main/java/com/example/epari/exam/controller/StudentExamController.java
  src/main/java/com/example/epari/exam/domain/Exam.java
  src/main/java/com/example/epari/exam/domain/ExamQuestion.java
  src/main/java/com/example/epari/exam/domain/MultipleChoiceQuestion.java
  src/main/java/com/example/epari/exam/domain/SubjectiveQuestion.java
  src/main/java/com/example/epari/exam/dto/request/ChoiceRequestDto.java
  src/main/java/com/example/epari/exam/dto/request/CreateQuestionRequestDto.java
  src/main/java/com/example/epari/exam/dto/request/UpdateQuestionRequestDto.java
  src/main/java/com/example/epari/exam/dto/response/ChoiceResponseDto.java
  src/main/java/com/example/epari/exam/dto/response/ExamQuestionResponseDto.java
  src/main/java/com/example/epari/exam/repository/ExamQuestionRepository.java
  src/main/java/com/example/epari/exam/repository/ExamRepository.java
  src/main/java/com/example/epari/exam/service/ExamFinder.java
  src/main/java/com/example/epari/exam/service/ExamQuestionService.java
  src/main/java/com/example/epari/exam/service/ExamService.java
  src/main/java/com/example/epari/exam/service/InstructorExamService.java
  src/main/java/com/example/epari/exam/service/StudentExamService.java
  src/test/java/com/example/epari/EpariBackendApplicationTests.java
Labels: enhancement

#71 [FEAT] 공지사항 프론트와 연동 시 기능 개선
  src/main/java/com/example/epari/board/controller/FileController.java
  src/main/java/com/example/epari/board/controller/NoticeController.java
  src/main/java/com/example/epari/board/service/NoticeService.java
Labels: enhancement

#76 [FEAT] 과제 수정 삭제 로직 구현, 첨부된 파일 다운로드 삭제 구현
  src/main/java/com/example/epari/assignment/controller/AssignmentController.java
  src/main/java/com/example/epari/assignment/controller/AssignmentFileController.java
  src/main/java/com/example/epari/assignment/domain/Assignment.java
  src/main/java/com/example/epari/assignment/repository/AssignmentFileRepository.java
  src/main/java/com/example/epari/assignment/repository/AssignmentRepository.java
  src/main/java/com/example/epari/assignment/service/AssignmentService.java
Labels: enhancement

#81 [FEAT] Cognito 연동 및 관리자 승인 프로세스
  .gitignore
  src/main/java/com/example/epari/admin/controller/AdminCourseController.java
  src/main/java/com/example/epari/admin/controller/AdminUserManagementController.java
  src/main/java/com/example/epari/admin/dto/ApprovalRequestDTO.java
  src/main/java/com/example/epari/admin/dto/CognitoUserDTO.java
  src/main/java/com/example/epari/admin/dto/CourseSearchResponseDTO.java
  src/main/java/com/example/epari/admin/exception/CognitoException.java
  src/main/java/com/example/epari/admin/exception/CourseNotFoundException.java
  src/main/java/com/example/epari/admin/service/AdminCourseService.java
  src/main/java/com/example/epari/admin/service/AdminUserService.java
  src/main/java/com/example/epari/admin/service/CognitoService.java
  src/main/java/com/example/epari/course/repository/CourseRepository.java
  src/main/java/com/example/epari/global/common/enums/UserRole.java
  src/main/java/com/example/epari/global/config/aws/AwsCognitoConfig.java
  src/main/java/com/example/epari/global/config/security/SecurityConfig.java
  src/main/java/com/example/epari/global/exception/ErrorCode.java
Labels: enhancement

#85 [FEAT] 과제 제출 관련 서비스 로직 구현
  src/main/java/com/example/epari/assignment/controller/AssignmentController.java
  src/main/java/com/example/epari/assignment/controller/SubmissionController.java
  src/main/java/com/example/epari/assignment/controller/SubmissionFileController.java
  src/main/java/com/example/epari/assignment/domain/AssignmentFile.java
  src/main/java/com/example/epari/assignment/domain/Submission.java
  src/main/java/com/example/epari/assignment/domain/SubmissionFile.java
  src/main/java/com/example/epari/assignment/dto/file/SubmissionFileResponseDto.java
  src/main/java/com/example/epari/assignment/dto/submission/GradeRequestDto.java
  src/main/java/com/example/epari/assignment/dto/submission/SubmissionRequestDto.java
  src/main/java/com/example/epari/assignment/dto/submission/SubmissionResponseDto.java
  src/main/java/com/example/epari/assignment/repository/SubmissionFileRepository.java
  src/main/java/com/example/epari/assignment/repository/SubmissionRepository.java
  src/main/java/com/example/epari/assignment/service/AssignmentService.java
  src/main/java/com/example/epari/assignment/service/SubmissionService.java
  src/main/java/com/example/epari/user/repository/StudentRepository.java
  src/test/resources/application.properties
  src/test/resources/application.yaml
Labels: enhancement

#79 [REFACTOR] 업로드 코드 개선 및 @EnableMethodSecurity 설정 변경
  src/main/java/com/example/epari/course/controller/CourseContentController.java
  src/main/java/com/example/epari/course/controller/CourseController.java
  src/main/java/com/example/epari/global/config/security/SecurityConfig.java
Labels: refactoring

#87 [FEAT] 시험 더미 데이터 추가 및 출석률, 학생별 시험 결과 조회
  src/main/java/com/example/epari/course/controller/AttendanceStatisticsController.java
  src/main/java/com/example/epari/course/dto/attendance/AttendanceStatResponseDto.java
  src/main/java/com/example/epari/course/repository/AttendanceRepository.java
  src/main/java/com/example/epari/course/service/AttendanceCalculationService.java
  src/main/java/com/example/epari/course/service/AttendanceStatisticsService.java
  src/main/java/com/example/epari/exam/controller/ExamResultController.java
  src/main/java/com/example/epari/exam/dto/request/ExamResultRequestDto.java
  src/main/java/com/example/epari/exam/dto/response/ExamResultResponseDto.java
  src/main/java/com/example/epari/exam/repository/ExamRepository.java
  src/main/java/com/example/epari/exam/repository/ExamResultRepository.java
  src/main/java/com/example/epari/exam/service/ExamResultService.java
  src/main/java/com/example/epari/global/exception/ErrorCode.java
  src/main/java/com/example/epari/global/exception/attendance/AttendanceFutureCourseException.java
  src/main/java/com/example/epari/global/exception/attendance/AttendanceNotFoundException.java
  src/main/java/com/example/epari/global/exception/course/CourseNotFoundException.java
  src/main/java/com/example/epari/global/exception/exam/ExamResultNotFoundException.java
  src/main/java/com/example/epari/global/init/InitDataLoader.java
Labels: enhancement

#89 [FEAT] 시험 상세 정보 조회 개선 및 사용자 권한별 조회 기능 구현
  src/main/java/com/example/epari/course/domain/Course.java
  src/main/java/com/example/epari/course/repository/CourseStudentRepository.java
  src/main/java/com/example/epari/exam/controller/ExamController.java
  src/main/java/com/example/epari/exam/controller/ExamSubmissionController.java
  src/main/java/com/example/epari/exam/domain/Exam.java
  src/main/java/com/example/epari/exam/domain/ExamResult.java
  src/main/java/com/example/epari/exam/domain/ExamScore.java
  src/main/java/com/example/epari/exam/dto/common/AnswerSubmissionDto.java
  src/main/java/com/example/epari/exam/dto/common/ExamStatistics.java
  src/main/java/com/example/epari/exam/dto/common/ExamSubmissionStatusDto.java
  src/main/java/com/example/epari/exam/dto/request/ExamRequestDto.java
  src/main/java/com/example/epari/exam/dto/response/ExamListResponseDto.java
  src/main/java/com/example/epari/exam/dto/response/ExamQuestionResponseDto.java
  src/main/java/com/example/epari/exam/dto/response/ExamResponseDto.java
  src/main/java/com/example/epari/exam/dto/response/ExamSummaryDto.java
  src/main/java/com/example/epari/exam/dto/response/QuestionImageResponseDto.java
  src/main/java/com/example/epari/exam/repository/ExamQuestionRepository.java
  src/main/java/com/example/epari/exam/repository/ExamRepository.java
  src/main/java/com/example/epari/exam/repository/ExamResultRepository.java
  src/main/java/com/example/epari/exam/service/ExamFinder.java
  src/main/java/com/example/epari/exam/service/ExamQuestionService.java
  src/main/java/com/example/epari/exam/service/ExamService.java
  src/main/java/com/example/epari/exam/service/ExamSubmissionService.java
  src/main/java/com/example/epari/global/common/enums/ExamStatus.java
  src/main/java/com/example/epari/global/config/security/checker/CourseSecurityChecker.java
  src/main/java/com/example/epari/global/exception/ErrorCode.java
  src/main/java/com/example/epari/global/validator/ExamQuestionValidator.java
  src/main/java/com/example/epari/user/repository/StudentRepository.java
Labels: enhancement

#92 [FIX] ExamSubmssionController 엔드포인트 수정
  src/main/java/com/example/epari/exam/controller/ExamSubmissionController.java
Labels: bug

#94 [FEAT] 비밀번호 찾기 기능을 위한 사용자 인증 체계 구현
  src/main/java/com/example/epari/global/auth/controller/AuthController.java
  src/main/java/com/example/epari/global/auth/service/AuthService.java
  src/main/java/com/example/epari/global/config/security/SecurityConfig.java
  src/main/java/com/example/epari/global/exception/ErrorCode.java
Labels: enhancement

#101 [FEAT] Redis 캐시 시스템 구축
  build.gradle
  src/main/java/com/example/epari/course/service/CurriculumService.java
  src/main/java/com/example/epari/global/config/RedisConfig.java
  src/main/resources/application-prod.yaml
Labels: enhancement

#103 [REFACTOR] 시험 목록 조회 시 강사 정보 및 출제 일자 추가
  src/main/java/com/example/epari/exam/controller/ExamController.java
  src/main/java/com/example/epari/exam/dto/response/ExamSummaryDto.java
Labels: refactoring

#107 [FIX] 시험 목록 조회 로직 수정
  src/main/java/com/example/epari/exam/controller/ExamSubmissionController.java
  src/main/java/com/example/epari/exam/dto/response/ExamSummaryDto.java
  src/main/java/com/example/epari/exam/service/ExamService.java
Labels: bug

#109 [FIX] 시험 목록 조회시 누락된 정보 수정
  src/main/java/com/example/epari/exam/dto/response/ExamSummaryDto.java
Labels: bug

#110 마이페이지 프로필 이미지 관리 및 비동기 처리 개선
  docker-compose.yml
  src/main/java/com/example/epari/global/config/AsyncConfig.java
  src/main/java/com/example/epari/user/controller/UserProfileController.java
  src/main/java/com/example/epari/user/service/UserProfileService.java
Labels: enhancement

#112 [REFACTOR] 시험 상세 조회 강사 정보 추가
  src/main/java/com/example/epari/exam/controller/ExamController.java
  src/main/java/com/example/epari/exam/dto/response/ExamResponseDto.java
  src/main/java/com/example/epari/global/init/InitDataLoader.java
Labels: refactoring

#115 [FEAT] 과제 제출물 조회 서비스 로직 구현
  src/main/java/com/example/epari/admin/service/AdminUserService.java
  src/main/java/com/example/epari/assignment/controller/CourseSubmissionController.java
  src/main/java/com/example/epari/assignment/controller/SubmissionController.java
  src/main/java/com/example/epari/assignment/domain/Submission.java
  src/main/java/com/example/epari/assignment/dto/assignment/AssignmentResponseDto.java
  src/main/java/com/example/epari/assignment/dto/submission/SubmissionResponseDto.java
  src/main/java/com/example/epari/assignment/repository/SubmissionRepository.java
  src/main/java/com/example/epari/assignment/service/SubmissionService.java
  src/main/java/com/example/epari/course/dto/course/CourseResponseDto.java
  src/main/java/com/example/epari/global/common/base/BaseUser.java
  src/main/java/com/example/epari/global/common/enums/SubmissionGrade.java
  src/main/java/com/example/epari/global/init/InitDataLoader.java
  src/main/java/com/example/epari/user/domain/Instructor.java
  src/main/java/com/example/epari/user/domain/Student.java
Labels: enhancement

#116 [REFACTOR] 강의 관련 유효성검사과 커스텀 예외 처리
  src/main/java/com/example/epari/course/controller/CourseContentController.java
  src/main/java/com/example/epari/course/controller/CourseController.java
  src/main/java/com/example/epari/course/service/AttendanceStatisticsService.java
  src/main/java/com/example/epari/course/service/CourseContentService.java
  src/main/java/com/example/epari/course/service/CourseService.java
  src/main/java/com/example/epari/global/common/service/S3FileService.java
  src/main/java/com/example/epari/global/exception/ErrorCode.java
  src/main/java/com/example/epari/global/exception/auth/InstructorNotFoundException.java
  src/main/java/com/example/epari/global/exception/course/CourseContentNotFoundException.java
  src/main/java/com/example/epari/global/exception/course/CourseDateInvalidException.java
  src/main/java/com/example/epari/global/exception/course/CourseInstructorMismatchException.java
  src/main/java/com/example/epari/global/exception/file/CourseContentNotFoundException.java
  src/main/java/com/example/epari/global/exception/file/CourseFileNotFoundException.java
  src/main/java/com/example/epari/global/exception/file/FileDeleteFailedException.java
  src/main/java/com/example/epari/global/exception/file/FileDownloadFailedException.java
  src/main/java/com/example/epari/global/exception/file/FileEmptyException.java
  src/main/java/com/example/epari/global/exception/file/FileSizeExceededException.java
  src/main/java/com/example/epari/global/exception/file/FileUploadFailedException.java
  src/main/java/com/example/epari/global/exception/file/InvalidFileTypeException.java
  src/main/java/com/example/epari/global/exception/file/InvalidFileUrlException.java
  src/main/java/com/example/epari/global/init/InitDataLoader.java
Labels: refactoring

#117 [FEAT] 관리자용 강의 관리 시스템 구현
  src/main/java/com/example/epari/admin/controller/AdminCourseController.java
  src/main/java/com/example/epari/admin/controller/AdminCourseStudentController.java
  src/main/java/com/example/epari/admin/controller/AdminInstructorController.java
  src/main/java/com/example/epari/admin/dto/AdminCourseListResponseDto.java
  src/main/java/com/example/epari/admin/dto/AdminCourseRequestDto.java
  src/main/java/com/example/epari/admin/dto/AvailableStudentResponseDTO.java
  src/main/java/com/example/epari/admin/dto/CourseStudentResponseDTO.java
  src/main/java/com/example/epari/admin/dto/CourseStudentUpdateRequestDTO.java
  src/main/java/com/example/epari/admin/dto/InstructorSearchResponseDTO.java
  src/main/java/com/example/epari/admin/repository/AdminCourseRepository.java
  src/main/java/com/example/epari/admin/repository/AdminCourseStudentRepository.java
  src/main/java/com/example/epari/admin/repository/AdminInstructorRepository.java
  src/main/java/com/example/epari/admin/repository/AdminStudentRepository.java
  src/main/java/com/example/epari/admin/service/AdminCourseService.java
  src/main/java/com/example/epari/admin/service/AdminCourseStudentService.java
  src/main/java/com/example/epari/admin/service/AdminInstructorService.java
  src/main/java/com/example/epari/course/repository/CourseRepository.java
  src/main/java/com/example/epari/global/config/RedisConfig.java
  src/main/java/com/example/epari/global/exception/ErrorCode.java
Labels: enhancement

#123 [FIX] @CacheEvict 관련 문제 해결
  src/main/java/com/example/epari/admin/service/AdminCourseService.java
  src/main/java/com/example/epari/admin/service/AdminCourseStudentService.java
Labels: bug

#124 [FEAT] 시험을 미응시한 학생의 결과도 조회 가능하도록 로직 수정
  src/main/java/com/example/epari/EpariBackendApplication.java
  src/main/java/com/example/epari/exam/controller/ExamSubmissionController.java
  src/main/java/com/example/epari/exam/controller/GradingController.java
  src/main/java/com/example/epari/exam/domain/Exam.java
  src/main/java/com/example/epari/exam/dto/common/ExamResultSummaryDto.java
  src/main/java/com/example/epari/exam/dto/response/ExamSummaryDto.java
  src/main/java/com/example/epari/exam/repository/ExamRepository.java
  src/main/java/com/example/epari/exam/service/ExamStatusService.java
  src/main/java/com/example/epari/exam/service/ExamSubmissionService.java
  src/main/java/com/example/epari/exam/service/GradingService.java
  src/main/java/com/example/epari/global/common/enums/ExamStatus.java
  src/main/resources/application.yaml
Labels: enhancement

#121 [REFACTOR] 과제 전체 조회 제목 정보 추가
  src/main/java/com/example/epari/assignment/dto/submission/SubmissionResponseDto.java
  src/main/java/com/example/epari/exam/controller/ExamSubmissionController.java
  src/main/java/com/example/epari/exam/dto/common/ExamResultSummaryDto.java
  src/main/java/com/example/epari/exam/dto/common/QuestionResultDto.java
  src/main/java/com/example/epari/exam/service/ExamSubmissionService.java
Labels: refactoring

#126 [FEAT] 수강중인 전체 학생 정보 조회
  src/main/java/com/example/epari/assignment/controller/SubmissionController.java
  src/main/java/com/example/epari/assignment/dto/submission/SubmissionResponseDto.java
  src/main/java/com/example/epari/assignment/repository/SubmissionRepository.java
  src/main/java/com/example/epari/assignment/service/SubmissionService.java
  src/main/java/com/example/epari/user/repository/StudentRepository.java
Labels: enhancement

#128 [FEAT] Google 로그인 기능 구현
  src/main/java/com/example/epari/global/auth/controller/AuthController.java
  src/main/java/com/example/epari/global/auth/service/AuthService.java
Labels: enhancement

#129 [FIX] 시험 응시 인원 조회 상태값 추가
  src/main/java/com/example/epari/exam/service/ExamService.java
Labels: bug

#135 [FEAT] 관리자 - 강사 승인 엔드포인트 및 비즈니스 로직 구현
  src/main/java/com/example/epari/admin/controller/AdminUserManagementController.java
  src/main/java/com/example/epari/admin/dto/InstructorApprovalRequestDTO.java
  src/main/java/com/example/epari/admin/dto/StudentApprovalRequestDTO.java
  src/main/java/com/example/epari/admin/exception/ApprovalException.java
  src/main/java/com/example/epari/admin/repository/AdminCourseStudentRepository.java
  src/main/java/com/example/epari/admin/repository/AdminInstructorRepository.java
  src/main/java/com/example/epari/admin/service/AdminUserService.java
  src/main/java/com/example/epari/admin/service/CognitoService.java
  src/main/java/com/example/epari/admin/service/UserApprovalManager.java
  src/main/java/com/example/epari/global/event/NotificationType.java
  src/main/java/com/example/epari/global/exception/ErrorCode.java
  src/main/resources/mail-templates/instructor-approved.html
  src/main/resources/mail-templates/student-approved.html
Labels: enhancement

#138 [REFACTOR] 과제 삭제 연관관계 해결, 커스텀 예외처리 사용
  src/main/java/com/example/epari/assignment/domain/Assignment.java
  src/main/java/com/example/epari/assignment/service/AssignmentService.java
  src/main/java/com/example/epari/assignment/service/SubmissionService.java
  src/main/java/com/example/epari/global/exception/ErrorCode.java
  src/main/java/com/example/epari/global/exception/assignment/AssignmentAccessDeniedException.java
  src/main/java/com/example/epari/global/exception/assignment/AssignmentInstructorMismatchException.java
  src/main/java/com/example/epari/global/exception/assignment/AssignmentInvalidException.java
  src/main/java/com/example/epari/global/exception/assignment/AssignmentNotFoundException.java
  src/main/java/com/example/epari/global/exception/assignment/SubmissionAccessDeniedException.java
  src/main/java/com/example/epari/global/exception/assignment/SubmissionInvalidException.java
  src/main/java/com/example/epari/global/exception/assignment/SubmissionNotFoundException.java
  src/main/java/com/example/epari/global/exception/assignment/SubmissionStudentMismatchException.java
  src/main/java/com/example/epari/global/exception/file/AssignmentFileNotFoundException.java
  src/main/java/com/example/epari/global/exception/file/SubmissionFileNotFoundException.java
  src/main/java/com/example/epari/user/repository/InstructorRepository.java
Labels: refactoring

#141 [FEAT] 과제 평가 시, 학생에게 이메일 전송
  src/main/java/com/example/epari/assignment/controller/SubmissionController.java
  src/main/java/com/example/epari/assignment/service/SubmissionService.java
  src/main/java/com/example/epari/global/event/NotificationType.java
  src/main/resources/application-prod.yaml
  src/main/resources/mail-templates/assignment-grade.html
Labels: enhancement

#145 [FIX] 테스트 빌드 에러 수정
  src/main/java/com/example/epari/assignment/service/SubmissionService.java
Labels: bug

#143 [FEAT] 공지사항 Quill 이미지 S3 저장 및 첨부파일 다운로드
  src/main/java/com/example/epari/board/controller/FileController.java
  src/main/java/com/example/epari/board/controller/NoticeController.java
  src/main/java/com/example/epari/board/domain/Notice.java
  src/main/java/com/example/epari/board/domain/NoticeFile.java
  src/main/java/com/example/epari/board/dto/NoticeRequestDto.java
  src/main/java/com/example/epari/board/dto/NoticeResponseDto.java
  src/main/java/com/example/epari/board/repository/NoticeRepository.java
  src/main/java/com/example/epari/board/service/NoticeService.java
  src/main/java/com/example/epari/global/common/service/S3FileService.java
Labels: enhancement

#147 [REAFCTOR] 사용하지 않는 메서드 삭제 및 주석 생성
  src/main/java/com/example/epari/exam/controller/ExamResultController.java
  src/main/java/com/example/epari/exam/controller/ExamSubmissionController.java
  src/main/java/com/example/epari/exam/controller/GradingController.java
  src/main/java/com/example/epari/exam/domain/Exam.java
  src/main/java/com/example/epari/exam/domain/ExamQuestion.java
  src/main/java/com/example/epari/exam/domain/ExamResult.java
  src/main/java/com/example/epari/exam/domain/ExamScore.java
  src/main/java/com/example/epari/exam/domain/MultipleChoiceQuestion.java
  src/main/java/com/example/epari/exam/domain/QuestionImage.java
  src/main/java/com/example/epari/exam/domain/SubjectiveQuestion.java
  src/main/java/com/example/epari/exam/dto/common/AnswerSubmissionDto.java
  src/main/java/com/example/epari/exam/dto/common/ExamResultDetailDto.java
  src/main/java/com/example/epari/exam/dto/common/ExamResultSummaryDto.java
  src/main/java/com/example/epari/exam/dto/common/ExamSubmissionStatusDto.java
  src/main/java/com/example/epari/exam/dto/common/QuestionResultDto.java
  src/main/java/com/example/epari/exam/dto/request/ChoiceRequestDto.java
  src/main/java/com/example/epari/exam/dto/request/CreateQuestionRequestDto.java
  src/main/java/com/example/epari/exam/dto/request/ExamResultRequestDto.java
  src/main/java/com/example/epari/exam/dto/request/UpdateQuestionRequestDto.java
  src/main/java/com/example/epari/exam/dto/response/ChoiceResponseDto.java
  src/main/java/com/example/epari/exam/dto/response/ExamQuestionResponseDto.java
  src/main/java/com/example/epari/exam/dto/response/ExamResponseDto.java
  src/main/java/com/example/epari/exam/dto/response/ExamResultResponseDto.java
  src/main/java/com/example/epari/exam/dto/response/ExamSummaryDto.java
  src/main/java/com/example/epari/exam/dto/response/QuestionImageResponseDto.java
  src/main/java/com/example/epari/exam/exception/GradingException.java
  src/main/java/com/example/epari/exam/exception/GradingNotPossibleException.java
  src/main/java/com/example/epari/exam/exception/InvalidScoreException.java
  src/main/java/com/example/epari/exam/repository/ExamQuestionRepository.java
  src/main/java/com/example/epari/exam/repository/ExamRepository.java
  src/main/java/com/example/epari/exam/repository/ExamResultRepository.java
  src/main/java/com/example/epari/exam/scheduler/AutoGradingScheduler.java
  src/main/java/com/example/epari/exam/service/ExamQuestionService.java
  src/main/java/com/example/epari/exam/service/ExamResultService.java
  src/main/java/com/example/epari/exam/service/ExamService.java
  src/main/java/com/example/epari/exam/service/ExamStatusService.java
  src/main/java/com/example/epari/exam/service/ExamSubmissionService.java
  src/main/java/com/example/epari/exam/service/GradingService.java
Labels: refactoring

#149 [FEAT] 테스트용 오프셋 기반 페이지네이션 구현
  src/main/java/com/example/epari/course/controller/CourseContentController.java
  src/main/java/com/example/epari/course/dto/content/PageResponse.java
  src/main/java/com/example/epari/course/repository/CourseContentRepository.java
  src/main/java/com/example/epari/course/service/CourseContentService.java
Labels: enhancement

#152 [FEAT] CSV 파일 임포트 로직 구현
  src/main/java/com/example/epari/course/controller/DataImportController.java
  src/main/java/com/example/epari/course/service/CsvImportService.java
Labels: enhancement
